---
functional:
  - Возможность зарегистрироваться 
  - Отображение ошибки при регистрации и введении некорректного логина или пароля
  - Возможность войти под своим логином и паролем
  - Отображение ошибки при вводе неправильного логина или пароля
  - Возможность просмотра рейтингов игроков.
  - Возможность играть с ботом.
  - Возможность играть с другом по ссылке.
  - Пользователь должен иметь возможность создавать игры.
  - Пользователь должен иметь возможность участвовать в существующих играх.
  - Пользователь должен иметь возможность решать задачи на выбранном языке программирования.
  - Пользователь должен видеть результаты запуска тестов и код соперника в реальном времени.
  - Пользователь должен иметь возможность общаться с соперниками и зрителями в чате.
  - Пользователь может выбрать один из доступных языков программирования (JavaScript, PHP, Python и Ruby) для решения задач
non-functional:
  - Удобство использования. сайт должен быть разработан с учетом удобства использования.
  - Производительность. сайт должен быть оптимизирован для скорости работы.
  - Безопасность. cайт должен быть безопасным и защищать данные пользователя (GDPR).
  - Мобильная оптимизация. cайт должен иметь мобильную версию. 
  - Мобильная оптимизация. сайт должен быть удобным на мобильных устройствах.
  - Совместимость. сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Масштабируемость. сайт должен быть способен обрабатывать большое количество трафика, например, 1000 одновременных пользователей.
implicit:
  - Разрабатываться с учетом мнения и пожеланий пользователей.
  - Открытый исходный код, так как проект является опен-сорсом, разрабатываемым сообществом.
  - Гибкая разработка без формулирования жестких требований, чтобы учитывать пользовательские идеи и предложения постепенно.
