---
functional:
  - Представление возможности соревноваться двум игрокам в решении задач и видеть написание кода друг у друга.
  - Возможность просмотра рейтингов игроков.
  - Возможность играть с ботом.
  - Возможность играть с другом по ссылке.
  - Возможность зарегистрироваться 
non-functional:
  - Удобство использования: сайт должен быть разработан с учетом удобства использования.
  - Производительность: сайт должен быть оптимизирован для скорости работы.
  - Безопасность: сайт должен быть безопасным и защищать данные пользователей.
  - Мобильная оптимизация: сайт должен быть удобным на мобильных устройствах.
  - Совместимость: сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Масштабируемость: сайт должен быть способен обрабатывать большое количество трафика, например, 1000 одновременных пользователей.
implicit:
  - Разрабатываться с учетом мнения и пожеланий пользователей.
  - Открытый исходный код, так как проект является опен-сорсом, разрабатываемым сообществом.
  - Гибкая разработка без формулирования жестких требований, чтобы учитывать пользовательские идеи и предложения постепенно.
